export const ADD_FAVOURITE = 'ADD_FAVOURITE'
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE'
export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE'
export const TOGGLE_CELSIUS = 'TOGGLE_CELSIUS'
export const ADD_CITIES_DATA = 'ADD_CITIES_DATA'

